import 'package:my_fitness_tracker/domain/gamification/achievement_entities.dart';

/// Predefined catalogue of achievements available in the app.
const AchievementCatalog kAchievementCatalog = <AchievementDefinition>[
  AchievementDefinition(
    id: 'achievement_first_routine',
    name: 'Primera rutina',
    description: 'Crea tu primera rutina personalizada.',
    type: AchievementType.routine,
    icon: 'assets/icons/achievement_routine.png',
    targetValue: 1,
  ),
  AchievementDefinition(
    id: 'achievement_consistent_week',
    name: 'Constante',
    description: 'Completa 7 días consecutivos entrenando.',
    type: AchievementType.streak,
    icon: 'assets/icons/achievement_fire.png',
    targetValue: 7,
  ),
  AchievementDefinition(
    id: 'achievement_warrior',
    name: 'Guerrero',
    description: 'Mantén un streak de 30 días consecutivos.',
    type: AchievementType.streak,
    icon: 'assets/icons/achievement_warrior.png',
    targetValue: 30,
  ),
  AchievementDefinition(
    id: 'achievement_lifter',
    name: 'Levantador',
    description: 'Acumula 10,000 kg de volumen total.',
    type: AchievementType.workout,
    icon: 'assets/icons/achievement_weight.png',
    targetValue: 10000,
  ),
  AchievementDefinition(
    id: 'achievement_titan',
    name: 'Titán',
    description: 'Acumula 100,000 kg de volumen total.',
    type: AchievementType.workout,
    icon: 'assets/icons/achievement_titan.png',
    targetValue: 100000,
  ),
  AchievementDefinition(
    id: 'achievement_dedicated',
    name: 'Dedicado',
    description: 'Completa 50 entrenamientos.',
    type: AchievementType.workout,
    icon: 'assets/icons/achievement_calendar.png',
    targetValue: 50,
  ),
  AchievementDefinition(
    id: 'achievement_centurion',
    name: 'Centuria',
    description: 'Completa 100 entrenamientos.',
    type: AchievementType.workout,
    icon: 'assets/icons/achievement_centurion.png',
    targetValue: 100,
  ),
  AchievementDefinition(
    id: 'achievement_transformation',
    name: 'Transformación',
    description: 'Pierde 5 kg respecto a tu registro inicial.',
    type: AchievementType.metric,
    icon: 'assets/icons/achievement_scale.png',
    targetValue: 5,
  ),
  AchievementDefinition(
    id: 'achievement_gain',
    name: 'Ganancia',
    description: 'Gana 5 kg de masa muscular.',
    type: AchievementType.metric,
    icon: 'assets/icons/achievement_muscle.png',
    targetValue: 5,
  ),
  AchievementDefinition(
    id: 'achievement_record',
    name: 'Récord personal',
    description: 'Registra tu primer PR en cualquier ejercicio.',
    type: AchievementType.personalRecord,
    icon: 'assets/icons/achievement_pr.png',
    targetValue: 1,
  ),
];
